version: "3.5"

services:
  nginx:
    build:
      context: .
      dockerfile: files/Dockerfile-nginx
    container_name: 'website-static-prod'
    labels:
      - "traefik.docker.network=backend"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host: matiasaguirre.com, matiasaguirre.net, matiasaguirre.dev;"
      - "traefik.basic.port=80"
      - "traefik.basic.protocol=http"

  traefik:
    image: traefik:1.7.6
    container_name: 'website-traefik-prod'
    depends_on:
      - nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./files/traefik/${WEBSITE_HOST:-matiasaguirre.com}/traefik.toml:/traefik.toml
